version: 2
updates:
# Root level package.json (Turborepo)
- package-ecosystem: "npm" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "turbo"
  commit-message:
    prefix: "chore(deps)"
    prefix-development: "chore(deps-dev)"
  groups:
    turborepo-deps:
      patterns:
      - "turbo"
      - "@turbo/*"

# Web App
- package-ecosystem: "npm"
  directory: "/web"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "web"
  groups:
    next-deps:
      patterns:
      - "next"
      - "@next/*"
    react-deps:
      patterns:
      - "react"
      - "react-dom"

# Admin App
- package-ecosystem: "npm"
  directory: "/admin"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "admin"
  groups:
    next-deps:
      patterns:
      - "next"
      - "@next/*"
    react-deps:
      patterns:
      - "react"
      - "react-dom"

# Sites App
- package-ecosystem: "npm"
  directory: "/space"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "sites"
  groups:
    next-deps:
      patterns:
      - "next"
      - "@next/*"
    react-deps:
      patterns:
      - "react"
      - "react-dom"

# Live Server
- package-ecosystem: "npm"
  directory: "/live" # Adjust path for your Node.js app
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "live"
  - "nodejs"

# Python service
- package-ecosystem: "pip"
  directory: "/apiserver" # Adjust path for your Python app
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "backend"
  - "python"

# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "ci-cd"
  - "dependencies"

# Docker dependencies
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies"
  - "docker"
